version: '3'
services:
  mongodb:
    image: mongo
    environment:
      MONGO_INITDB_ROOT_USERNAME: mongo
      MONGO_INITDB_ROOT_PASSWORD: root
    ports:
      - "27017:27017"
    volumes:
      - ./mongodb_data:/data/db
  postgresql:
    image: postgres
    environment:
      POSTGRES_PASSWORD: root
    ports:
      - 5432:5432
    volumes:
      - ./postgresql_data:/var/lib/postgresql/data